### ISSUE TITLE
sh.CommandNotFound: postgres when following documentation about setting up a local development environment 

### ISSUE THREAD

**Issue by aless80** [devilry/devilry-django#1097]
I am following the documentation here [Setup a local development environment](https://devilry.readthedocs.io/en/latest/developer/gettingstarted.html#create-a-database) using Linux but I get the error: sh.CommandNotFound: postgres: 

```
(devilry-django) amarin $ ievv recreate_devdb
[INFO 2018-12-18 11:42:11,700 root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
[INFO 2018-12-18 11:42:11,736 root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/ievv_opensource/ievvtasks_development/management/commands/ievvtasks_recreate_devdb.py", line 18, in handle
    management.call_command('dbdev_reinit')
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django_dbdev/management/commands/_base.py", line 24, in handle
    self.dbdev_handle()
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django_dbdev/management/commands/dbdev_reinit.py", line 8, in dbdev_handle
    self.dbdev_backend.destroy()
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django_dbdev/management/commands/_base.py", line 52, in dbdev_backend
    return backendregistry.backends[self._dbengine](self)
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/django_dbdev/backends/postgres.py", line 39, in __init__
    self.postgres = Command(postgres_executable).bake(
  File "/home/amarin/devilry-django/devilry-django/local/lib/python2.7/site-packages/sh.py", line 1202, in __init__
    raise CommandNotFound(path)
sh.CommandNotFound: postgres
```

I get the same error when I try "ievv devrun". I follow the isntructions and these commands adapted from the docs work fine: 
```
amarin $ sudo apt-get install build-essential python-dev python-virtualenv libncurses5-dev virtualenvwrapper libxslt1-dev libxml2 libxml2-dev zlib1g-dev libpq-dev
amarin $ cd devilry-django
amarin $ virtualenv -p /usr/bin/python devilry-django
amarin $ source ./devilry-django/bin/activate
(devilry-django) amarin $ pip install -r requirements/development.txt
```

I checked that python and pip are version 2.7. I believe postgres is fine, I can log to psql interface using postgres or my username amarin

**Comment by torgeirl** [comment]
My guess is that this had to do with Python 2.x, which we dropped support for in Devilry 4.0 (released in April 2019).
