### ISSUE TITLE
The devilry_detektor app stops processing halfway through parsing the code

### ISSUE THREAD

**Issue by espenak** [devilry/devilry-django#621]
No idea why, but if it crashes with an exception, there may be something wrong with the Celery exception logging setup since the task seems to be completed successfully, and no errors are in the logs.

**Comment by tworide** [comment]
TypeError('coercing to Unicode: need string or buffer, NoneType found',)
Traceback (most recent call last):
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/devilry/devilry_detektor/tasks.py", line 191, in run_detektor_on_assignment
    assignmentparser.run_detektor()
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/devilry/devilry_detektor/tasks.py", line 151, in run_detektor
    self._process_deliveries()
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/devilry/devilry_detektor/tasks.py", line 166, in _process_deliveries
    self._process_delivery(delivery)
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/devilry/devilry_detektor/tasks.py", line 170, in _process_delivery
    process_delivery_runner.run_detektor()
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/devilry/devilry_detektor/tasks.py", line 125, in run_detektor
    parser.parse(parseresult, filemeta.get_all_data_as_string())
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/detektor/languageparser/base.py", line 122, in parse
    parseresult.parsed_functions = self.parse_functions(sourcecode)
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/detektor/languageparser/base.py", line 103, in parse_functions
    for extractedfunction in self.extract_functionsourcecode(sourcecode):
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/detektor/languageparser/java.py", line 38, in extract_functionsourcecode
    return self.function_extractor.extract(sourcecode)
  File "/hom/tdevilry/devilrydeploy/venv/lib/python2.7/site-packages/detektor/functionextractor/clike.py", line 35, in extract
    returntype = unicode(matches['returntype'], 'utf-8', 'replace')
TypeError: coercing to Unicode: need string or buffer, NoneType found
